### ISSUE TITLE
Uncaught TypeError: Cannot read property 'removeItem' of null

### ISSUE THREAD

**Issue by EFTEKHER** [jdtzmn/touchbar-run#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.49.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Home Single Language
**Thrown From**: [touchbar-run](https://github.com/jdtzmn/touchbar-run) package 0.1.1

### Stack Trace

Uncaught TypeError: Cannot read property 'removeItem' of null

```
At C:\Users\eftek\.atom\packages\touchbar-run\lib\touchbar-run.js:97

TypeError: Cannot read property 'removeItem' of null
    at Object.addScriptsToTouchbar (/packages/touchbar-run/lib/touchbar-run.js:97:29)
    at /packages/touchbar-run/lib/touchbar-run.js:26:102
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1201500)
    at Emitter.emit (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:1202941)
    at PaneContainer.didChangeActiveItemOnPane (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:447410)
    at PaneContainer.didActivatePane (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:446887)
    at Pane.activate (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:464305)
    at Pane.focus (~/AppData/Local/atom/app-1.49.0/resources/app/static/<embedded>:11:455748)
    at HTMLElement.handleFocus (/app.asar/src/pane-element.js:41:20)
```

### Commands

```
     -8:31.2.0 application:open (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -7:51.7.0 core:save-as (ul.list-inline.tab-bar.inset-panel)
     -7:34.1.0 core:backspace (input.hidden-input)
     -7:29.1.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -7:27.3.0 core:backspace (input.hidden-input)
     -7:20.1.0 editor:newline (input.hidden-input)
     -7:14.4.0 core:move-right (input.hidden-input)
  5x -7:14 editor:newline (input.hidden-input)
 59x -3:07.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
gpp-compiler 3.0.7 
javascript-regex 2.0.0 
Quick-JavaScript 2.2.0 
run 0.0.1 
run-script 4.0.1 
script 3.26.0 
touchbar-registry 0.3.2 
touchbar-run 0.1.1 
```

**Comment by jdtzmn** [comment]
@EFTEKHER This plugin is intended for use on macOS. In addition, it seems that the underlying package it relies on, [touchbar-registry](https://github.com/haklop/touchbar-registry), is not supported by Atom 1.49. See an open issue addressing that problem [here](https://github.com/haklop/touchbar-registry/issues/2). I don't believe this is a problem with the touchbar-run package itself, so I am going to close this issue.
